language: java
services: mongodb
script: cd "BSPQ20-E1" && mvn clean compile datanucleus:schema-create test
notifications:
  email:
    recipients:
      - pablo.villacorta@opendeusto.es
      - mikelmoreno23@opendeusto.es
      - vasilis.matthaios@opendeusto.es
      - erik.saenzdeugarte@opendeusto.es
      - ivangarcia96@opendeusto.es
    on_success: never
    on_failure: always